[Settings]
 LogLevel = "debug"
#LogLevel = "info"
UseAuth = false
# TokenTTL min
TokenTTL = 1
LogPath = "server_cti.log"

[CtiAPI]
Scheme = "ws"
Path = "/ws"
Host = "192.168.223.50"
Port = "8098"

[HttpAPI]
Scheme = "http"
Host = "localhost"
Port = "9595"

[DB]
Host = "localhost"
Port = "5432"
DBname = "cti"
User = "cti"
Password = "cti"
